/'
elonaの黒猫エンチャント試行作業の自動化ツール
要件として以下を満たすこと
・ゲーム画面の画像認識を行い、画像の文字列に応じた処理を行う
・セーブデータの退避などファイル操作を行う
・Escキーを押下することで自動操作を途中で停止できること
・Escキー押下による停止要求は、各待機処理及び各ループ反復のたびに確認すること
・開発環境、フレームワークを含めて無料で開発および利用できること
・オフライン環境で実行できるデスクトップアプリであること

要素は以下の通り
・言語：C#
・画像認識：Windows.Graphics.Captureでゲームウィンドウをキャプチャして、Windows.Media.OcrのOCR用APIで処理を行う
'/
@startuml
start
    'カウンタの初期化
    :試行回数カウンタ = 0;
    :ペロペロ成功カウンタ = 0;
    '黒猫によるペロペロエンチャ付与を3回成功、もしくは試行回数が5回になったら終了
    while (ペロペロ成功カウンタ < 3 かつ 試行回数カウンタ < 5)
        '試行回数を加算
        :試行回数カウンタ += 1;

        '今回の試行でペロペロが成功したかどうかのフラグの初期化
        :ペロペロ成功済みフラグ = false;

        'elona.exeを起動する。フルパスは「"C:\インストール\ゲーム\elona\elona.exe"」
        :elona.exe を起動する;

        :画面に「冒険の道標」が表示されるまで待機;
        :Enter キーを押下;

        :画面に「冒険者の選択」が表示されるまで待機;
        :Enter キーを押下;

        :画面に「Welcome traveler!」が表示されるまで待機;

        '付近の相手にダメージ無しの攻撃を行い、戦闘状態に入る
        :9 キーを押下;

        '黒猫による攻撃を最大5回まで試行する
        :黒猫攻撃カウンタ = 0;
        while (黒猫攻撃カウンタ < 5 かつ ペロペロ成功済みフラグ == false)
            :1秒待機;
            :5 キーを押下;
            :1秒待機;
            if (ペロペロ表示?) then (Yes)
                :ペロペロ成功カウンタ += 1;
                :ペロペロ成功済みフラグ = true;

                'ゲームelona.exeのデータを保存して終了する
                :「Shift + s」 キーを押下;
                :画面に「これまでの冒険を記録して終了する？」が表示されるまで待機;
                :Enter キーを押下;
                :1秒待機;
                :Enter キーを押下;

                '成功したセーブデータの保存。
                'コピー元は「"C:\インストール\ゲーム\elona\save"」フォルダ
                'コピー先は「C:\インストール\ゲーム\elona\bk_save\yyyymmdd_hhmmss_黒猫トライ_save」という名称のフォルダにする。
                'サブディレクトリごとコピーすることに注意。
                :saveフォルダをコピーしてセーブデータを保存する;
                :1秒待機;

                '「"C:\インストール\ゲーム\elona\save"」フォルダを削除する。
                :saveフォルダの削除;
                :1秒待機;

                '「"C:\インストール\ゲーム\elona\bk_save\黒猫トライ前\save"」フォルダをサブディレクトリごとコピーして「"C:\インストール\ゲーム\elona\save"」として貼り付ける
                :保存しておいた元の状態のsaveフォルダで置き換える;
            endif
            :黒猫攻撃カウンタ += 1;
        endwhile

    'ペロペロが成功していない場合、ここでelona.exeを終了する
    'ペロペロ成功時は「Shift + s」でelona.exeを終了済みのためここでは何もしない
    if (ペロペロ成功済みフラグ == false) then (yes)
        :Alt + F4 キーを押下;
    endif

    'Escキー押下で処理を中断する
    if (停止要求がある) then (yes)
        stop
    endif
    end while
stop
@enduml
